use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Mutex;
use utoipa::ToSchema;

/// Per-clinic activity snapshot used by the timelapse heatmap.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct ClinicActivity {
    pub clinic_id: String,
    pub city: String,
    pub state: String,
    pub active_patients: usize,
}

/// State of a running (or completed) timelapse simulation.
/// Updated once per hour-window by `run_timelapse` and read by `GET /simulate/heatmap`.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct TimelapseState {
    /// Current simulated date, e.g. "2026-03-15"
    pub simulation_day: String,
    /// 1-based day counter
    pub day_number: usize,
    /// Total days in the timelapse
    pub total_days: usize,
    /// Current simulated hour (8..17)
    pub sim_hour: u32,
    /// Per-clinic appointment counts for the current hour-window
    pub clinics: Vec<ClinicActivity>,
    /// True when the timelapse has finished all days
    pub is_complete: bool,
}

/// Row counts from the last completed populate or simulate run.
/// Populated by POST /populate (Aurora DSQL fields) and POST /simulate (DynamoDB fields).
///
/// Aurora DSQL fields — set by POST /populate:
///   insurance_companies, insurance_plans, clinics, providers, patients,
///   emergency_contacts, patient_demographics, patient_insurance,
///   clinic_schedules, appointments, medical_records, patient_visits, patient_vitals
///
/// DynamoDB fields — set by POST /simulate (day-of visit writes):
///   dynamo_patient_visits, dynamo_patient_vitals
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SimulationCounts {
    pub insurance_companies: usize,
    pub insurance_plans: usize,
    pub clinics: usize,
    pub providers: usize,
    pub patients: usize,
    pub emergency_contacts: usize,
    pub patient_demographics: usize,
    pub patient_insurance: usize,
    pub clinic_schedules: usize,
    pub appointments: usize,
    pub medical_records: usize,
    /// Aurora DSQL patient_visit rows generated by the last populate run.
    pub patient_visits: usize,
    /// Aurora DSQL patient_vitals rows generated by the last populate run.
    pub patient_vitals: usize,
    /// DynamoDB patient_visit records written by the last simulate run.
    pub dynamo_patient_visits: usize,
    /// DynamoDB patient_vitals records written by the last simulate run.
    pub dynamo_patient_vitals: usize,
}

/// Progress of an in-flight Aurora reset operation.
/// Exposed via `GET /simulate/status` so the UI can show per-table deletion progress.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct ResetProgress {
    /// Human-readable name of the table currently being deleted
    pub current_table: String,
    /// Number of tables fully deleted so far
    pub tables_done: usize,
    /// Total number of tables to delete
    pub total_tables: usize,
    /// Cumulative rows deleted across all tables
    pub rows_deleted: u64,
    /// True once every table has been cleared
    pub is_complete: bool,
}

/// Progress of an in-flight populate operation.
/// Exposed via `GET /simulate/status` so the UI can show per-step progress.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct PopulateProgress {
    /// Human-readable name of the step currently executing
    pub current_step: String,
    /// Number of steps fully completed so far
    pub steps_done: usize,
    /// Total number of steps in the populate pipeline
    pub total_steps: usize,
    /// Cumulative rows written across all completed steps
    pub rows_written: u64,
    /// True once every step has finished
    pub is_complete: bool,
}

/// Progress of a DynamoDB operation (reset or sync).
/// Exposed via `GET /simulate/status` so the UI can show a progress bar.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct DynamoProgress {
    /// Human-readable operation label, e.g. "Resetting DynamoDB" or "Syncing to DynamoDB"
    pub operation: String,
    /// Table currently being processed
    pub current_table: String,
    /// Tables fully processed so far
    pub tables_done: usize,
    /// Total tables to process
    pub total_tables: usize,
    /// Items processed so far (deleted or written)
    pub items_processed: u64,
    /// Total items to process (0 if unknown, e.g. during scan-delete)
    pub total_items: u64,
    /// True once the operation has finished
    pub is_complete: bool,
}

/// Global state for the data simulator.
/// Tracks whether a simulation is running and stores metrics from the last run.
pub struct SimulatorState {
    /// Flag indicating if a simulation is currently running
    pub running: AtomicBool,

    /// Timestamp of the last completed simulation run
    pub last_run: Mutex<Option<DateTime<Utc>>>,

    /// Row counts from the last completed simulation run
    pub counts: Mutex<SimulationCounts>,

    /// Timelapse heatmap state (None when no timelapse has been run)
    pub timelapse: Mutex<Option<TimelapseState>>,

    /// Aurora reset progress (None when no reset is running)
    pub reset_progress: Mutex<Option<ResetProgress>>,

    /// Populate progress (None when no populate is running)
    pub populate_progress: Mutex<Option<PopulateProgress>>,

    /// DynamoDB operation progress (reset or sync — None when idle)
    pub dynamo_progress: Mutex<Option<DynamoProgress>>,
}

impl SimulatorState {
    /// Create a new SimulatorState with all fields initialized to defaults.
    pub fn new() -> Self {
        SimulatorState {
            running: AtomicBool::new(false),
            last_run: Mutex::new(None),
            counts: Mutex::new(SimulationCounts::default()),
            timelapse: Mutex::new(None),
            reset_progress: Mutex::new(None),
            populate_progress: Mutex::new(None),
            dynamo_progress: Mutex::new(None),
        }
    }

    /// Check if a simulation is currently running (non-blocking).
    pub fn is_running(&self) -> bool {
        self.running.load(Ordering::SeqCst)
    }

    /// Attempt to mark the simulator as running.
    /// Returns true if the simulator was idle and is now marked as running.
    /// Returns false if a simulation was already in progress.
    pub fn try_start(&self) -> bool {
        self.running
            .compare_exchange(false, true, Ordering::SeqCst, Ordering::SeqCst)
            .is_ok()
    }

    /// Mark the simulator as stopped.
    pub fn stop(&self) {
        self.running.store(false, Ordering::SeqCst);
    }

    /// Get the timestamp of the last completed run (if any).
    pub fn get_last_run(&self) -> Option<DateTime<Utc>> {
        *self.last_run.lock().expect("state mutex poisoned")
    }

    /// Update the last run timestamp to now.
    pub fn set_last_run(&self, timestamp: DateTime<Utc>) {
        *self.last_run.lock().expect("state mutex poisoned") = Some(timestamp);
    }

    /// Get a clone of the current simulation counts.
    pub fn get_counts(&self) -> SimulationCounts {
        self.counts.lock().expect("state mutex poisoned").clone()
    }

    /// Update the simulation counts.
    pub fn set_counts(&self, counts: SimulationCounts) {
        *self.counts.lock().expect("state mutex poisoned") = counts;
    }

    /// Get a clone of the current timelapse state (if any).
    pub fn get_timelapse(&self) -> Option<TimelapseState> {
        self.timelapse.lock().expect("state mutex poisoned").clone()
    }

    /// Update the timelapse state.
    pub fn set_timelapse(&self, state: Option<TimelapseState>) {
        *self.timelapse.lock().expect("state mutex poisoned") = state;
    }

    /// Get a clone of the current reset progress (if any).
    pub fn get_reset_progress(&self) -> Option<ResetProgress> {
        self.reset_progress.lock().expect("state mutex poisoned").clone()
    }

    /// Update the reset progress.
    pub fn set_reset_progress(&self, progress: Option<ResetProgress>) {
        *self.reset_progress.lock().expect("state mutex poisoned") = progress;
    }

    /// Get a clone of the current populate progress (if any).
    pub fn get_populate_progress(&self) -> Option<PopulateProgress> {
        self.populate_progress.lock().expect("state mutex poisoned").clone()
    }

    /// Update the populate progress.
    pub fn set_populate_progress(&self, progress: Option<PopulateProgress>) {
        *self.populate_progress.lock().expect("state mutex poisoned") = progress;
    }

    /// Get a clone of the current DynamoDB operation progress (if any).
    pub fn get_dynamo_progress(&self) -> Option<DynamoProgress> {
        self.dynamo_progress.lock().expect("state mutex poisoned").clone()
    }

    /// Update the DynamoDB operation progress.
    pub fn set_dynamo_progress(&self, progress: Option<DynamoProgress>) {
        *self.dynamo_progress.lock().expect("state mutex poisoned") = progress;
    }
}

impl Default for SimulatorState {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_simulator_state_creation() {
        let state = SimulatorState::new();
        assert!(!state.is_running());
        assert_eq!(state.get_last_run(), None);
    }

    #[test]
    fn test_try_start_transitions() {
        let state = SimulatorState::new();

        // First attempt should succeed
        assert!(state.try_start());
        assert!(state.is_running());

        // Second attempt should fail (already running)
        assert!(!state.try_start());
        assert!(state.is_running());

        // After stop, should be able to start again
        state.stop();
        assert!(!state.is_running());
        assert!(state.try_start());
    }

    #[test]
    fn test_counts_updates() {
        let state = SimulatorState::new();
        let mut counts = SimulationCounts::default();
        counts.patients = 100;
        counts.appointments = 50;

        state.set_counts(counts.clone());
        let retrieved = state.get_counts();

        assert_eq!(retrieved.patients, 100);
        assert_eq!(retrieved.appointments, 50);
    }

    #[test]
    fn test_last_run_timestamp() {
        let state = SimulatorState::new();
        let now = Utc::now();

        state.set_last_run(now);
        let retrieved = state.get_last_run();

        assert!(retrieved.is_some());
        assert_eq!(retrieved.unwrap(), now);
    }
}
