-- =============================================================================
-- VitalFold Engine — Full Database Schema
-- Aurora DSQL (PostgreSQL-compatible)
--
-- This file creates ALL tables needed by the application:
--   1. public.users         — authentication
--   2. vital_fold.*         — 13 healthcare simulation tables
--
-- Safe to re-run: DROP SCHEMA CASCADE + IF NOT EXISTS on public tables.
-- Invoked by POST /admin/init-db from the admin dashboard.
-- =============================================================================

-- Drop and recreate the vital_fold schema (all simulation data)
DROP SCHEMA IF EXISTS vital_fold CASCADE;
CREATE SCHEMA vital_fold;

-- =============================================================================
-- PUBLIC SCHEMA — Authentication
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.users (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX ASYNC IF NOT EXISTS idx_users_email ON public.users (email);


-- =============================================================================
-- 1. insurance_company — 7 fixed carriers (no FK dependencies)
-- =============================================================================
CREATE TABLE vital_fold.insurance_company (
    company_id       UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    company_name     VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    phone_number     VARCHAR(20)  NOT NULL,
    tax_id_number    INT          NOT NULL
);

CREATE INDEX ASYNC IF NOT EXISTS idx_insurance_company_name
    ON vital_fold.insurance_company (company_name);
CREATE INDEX ASYNC IF NOT EXISTS idx_insurance_company_tax_id
    ON vital_fold.insurance_company (tax_id_number);


-- =============================================================================
-- 2. insurance_plan — N plans per company
-- =============================================================================
CREATE TABLE vital_fold.insurance_plan (
    insurance_plan_id  UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_name          VARCHAR(255)   NOT NULL,
    company_id         UUID           NOT NULL,
    deductible_amount  DECIMAL(10, 2) NOT NULL,
    copay_amount       DECIMAL(10, 2) NOT NULL,
    prior_auth_required BOOLEAN       NOT NULL,
    active_plan        BOOLEAN        NOT NULL,
    active_start_date  DATE           NOT NULL
);

CREATE INDEX ASYNC IF NOT EXISTS idx_insurance_plan_company_id
    ON vital_fold.insurance_plan (company_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_insurance_plan_company_active
    ON vital_fold.insurance_plan (company_id, active_plan);


-- =============================================================================
-- 3. provider — BIGINT identity PK (CACHE 1 for ~50 rows)
-- =============================================================================
CREATE TABLE vital_fold.provider (
    provider_id   BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (CACHE 1),
    first_name    VARCHAR(255) NOT NULL,
    last_name     VARCHAR(255) NOT NULL,
    specialty     VARCHAR(255) NOT NULL,
    license_type  VARCHAR(50)  NOT NULL,
    phone_number  VARCHAR(20)  NOT NULL,
    email         VARCHAR(255) NOT NULL
);

CREATE INDEX ASYNC IF NOT EXISTS idx_provider_name
    ON vital_fold.provider (last_name, first_name);
CREATE INDEX ASYNC IF NOT EXISTS idx_provider_specialty
    ON vital_fold.provider (specialty);


-- =============================================================================
-- 4. clinic — BIGINT identity PK (CACHE 1 for 10 fixed rows)
-- =============================================================================
CREATE TABLE vital_fold.clinic (
    clinic_id      BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (CACHE 1),
    clinic_name    VARCHAR(255) NOT NULL,
    region         VARCHAR(255) NOT NULL,
    street_address VARCHAR(255) NOT NULL,
    city           VARCHAR(255) NOT NULL,
    state          VARCHAR(50)  NOT NULL,
    zip_code       VARCHAR(10)  NOT NULL,
    phone_number   VARCHAR(20)  NOT NULL,
    email          VARCHAR(255) NOT NULL
);

CREATE INDEX ASYNC IF NOT EXISTS idx_clinic_region
    ON vital_fold.clinic (region);
CREATE INDEX ASYNC IF NOT EXISTS idx_clinic_city_state
    ON vital_fold.clinic (city, state);


-- =============================================================================
-- 5. patient — UUID PK (high volume: 50K default)
-- =============================================================================
CREATE TABLE vital_fold.patient (
    patient_id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name           VARCHAR(255) NOT NULL,
    last_name            VARCHAR(255) NOT NULL,
    middle_name          VARCHAR(255),
    date_of_birth        DATE         NOT NULL,
    street_address       VARCHAR(255) NOT NULL,
    city                 VARCHAR(255) NOT NULL,
    state                VARCHAR(50)  NOT NULL,
    zip_code             VARCHAR(10)  NOT NULL,
    phone_number         VARCHAR(20)  NOT NULL,
    email                VARCHAR(255) NOT NULL,
    registration_date    DATE         NOT NULL,
    emergency_contact_id VARCHAR(255) NOT NULL
);

CREATE INDEX ASYNC IF NOT EXISTS idx_patient_name
    ON vital_fold.patient (last_name, first_name);
CREATE INDEX ASYNC IF NOT EXISTS idx_patient_dob
    ON vital_fold.patient (date_of_birth);
CREATE INDEX ASYNC IF NOT EXISTS idx_patient_email
    ON vital_fold.patient (email);


-- =============================================================================
-- 6. emergency_contact — 1:1 with patient
-- =============================================================================
CREATE TABLE vital_fold.emergency_contact (
    emergency_contact_id UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id           UUID         NOT NULL,
    first_name           VARCHAR(255) NOT NULL,
    last_name            VARCHAR(255) NOT NULL,
    relationship         VARCHAR(255) NOT NULL,
    phone_number         VARCHAR(20)  NOT NULL,
    email                VARCHAR(255) NOT NULL
);

CREATE INDEX ASYNC IF NOT EXISTS idx_emergency_contact_patient_id
    ON vital_fold.emergency_contact (patient_id);


-- =============================================================================
-- 7. patient_demographics — 1:1 with patient
-- =============================================================================
CREATE TABLE vital_fold.patient_demographics (
    demographics_id UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id      UUID         NOT NULL,
    first_name      VARCHAR(255) NOT NULL,
    last_name       VARCHAR(255) NOT NULL,
    date_of_birth   DATE         NOT NULL,
    age             INT          NOT NULL,
    ssn             VARCHAR(11)  NOT NULL,
    ethnicity       VARCHAR(255) NOT NULL,
    birth_gender    VARCHAR(50)  NOT NULL
);

CREATE INDEX ASYNC IF NOT EXISTS idx_patient_demographics_patient_id
    ON vital_fold.patient_demographics (patient_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_patient_demographics_ssn
    ON vital_fold.patient_demographics (ssn);


-- =============================================================================
-- 8. patient_insurance — 1+ per patient
-- =============================================================================
CREATE TABLE vital_fold.patient_insurance (
    patient_insurance_id UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id           UUID         NOT NULL,
    insurance_plan_id    UUID         NOT NULL,
    policy_number        VARCHAR(255) NOT NULL,
    coverage_start_date  DATE         NOT NULL,
    coverage_end_date    DATE
);

CREATE INDEX ASYNC IF NOT EXISTS idx_patient_insurance_patient_id
    ON vital_fold.patient_insurance (patient_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_patient_insurance_plan_id
    ON vital_fold.patient_insurance (insurance_plan_id);


-- =============================================================================
-- 9. clinic_schedule — provider-clinic-day combinations
-- =============================================================================
CREATE TABLE vital_fold.clinic_schedule (
    schedule_id  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    clinic_id    BIGINT      NOT NULL,
    provider_id  BIGINT      NOT NULL,
    day_of_week  VARCHAR(20) NOT NULL,
    start_time   TIME        NOT NULL,
    end_time     TIME        NOT NULL
);

CREATE INDEX ASYNC IF NOT EXISTS idx_clinic_schedule_clinic_day
    ON vital_fold.clinic_schedule (clinic_id, day_of_week);
CREATE INDEX ASYNC IF NOT EXISTS idx_clinic_schedule_provider_day
    ON vital_fold.clinic_schedule (provider_id, day_of_week);


-- =============================================================================
-- 10. appointment — provider fills 36 slots/day at their clinic
-- =============================================================================
CREATE TABLE vital_fold.appointment (
    appointment_id       UUID      PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id           UUID      NOT NULL,
    provider_id          BIGINT    NOT NULL,
    clinic_id            BIGINT    NOT NULL,
    appointment_datetime TIMESTAMP NOT NULL,
    reason_for_visit     VARCHAR(255) NOT NULL
);

CREATE INDEX ASYNC IF NOT EXISTS idx_appointment_patient_id
    ON vital_fold.appointment (patient_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_appointment_datetime
    ON vital_fold.appointment (appointment_datetime);
CREATE INDEX ASYNC IF NOT EXISTS idx_appointment_clinic_datetime
    ON vital_fold.appointment (clinic_id, appointment_datetime);
CREATE INDEX ASYNC IF NOT EXISTS idx_appointment_provider_datetime
    ON vital_fold.appointment (provider_id, appointment_datetime);


-- =============================================================================
-- 11. medical_record — 1+ per appointment
-- =============================================================================
CREATE TABLE vital_fold.medical_record (
    medical_record_id UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id        UUID         NOT NULL,
    provider_id       BIGINT       NOT NULL,
    clinic_id         BIGINT       NOT NULL,
    record_date       TIMESTAMP    NOT NULL,
    diagnosis         VARCHAR(255) NOT NULL,
    treatment         VARCHAR(255) NOT NULL
);

CREATE INDEX ASYNC IF NOT EXISTS idx_medical_record_patient_id
    ON vital_fold.medical_record (patient_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_medical_record_patient_date
    ON vital_fold.medical_record (patient_id, record_date);


-- =============================================================================
-- 12. patient_visit — 1:1 with appointment
-- =============================================================================
CREATE TABLE vital_fold.patient_visit (
    patient_visit_id        UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    appointment_id          UUID           NOT NULL,
    patient_id              UUID           NOT NULL,
    clinic_id               BIGINT         NOT NULL,
    provider_id             BIGINT         NOT NULL,
    checkin_time            TIMESTAMP      NOT NULL,
    checkout_time           TIMESTAMP,
    provider_seen_time      TIMESTAMP,
    ekg_usage               BOOLEAN        NOT NULL,
    estimated_copay         DECIMAL(10, 2) NOT NULL,
    creation_time           TIMESTAMP      NOT NULL,
    record_expiration_epoch BIGINT         NOT NULL
);

CREATE INDEX ASYNC IF NOT EXISTS idx_patient_visit_appointment_id
    ON vital_fold.patient_visit (appointment_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_patient_visit_patient_id
    ON vital_fold.patient_visit (patient_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_patient_visit_clinic_id
    ON vital_fold.patient_visit (clinic_id);


-- =============================================================================
-- 13. patient_vitals — 1:1 with patient_visit
-- =============================================================================
CREATE TABLE vital_fold.patient_vitals (
    patient_visit_id        UUID          PRIMARY KEY,
    patient_id              UUID          NOT NULL,
    clinic_id               BIGINT        NOT NULL,
    provider_id             BIGINT        NOT NULL,
    height                  DECIMAL(5, 2) NOT NULL,
    weight                  DECIMAL(5, 2) NOT NULL,
    blood_pressure          VARCHAR(20)   NOT NULL,
    heart_rate              INT           NOT NULL,
    temperature             DECIMAL(4, 1) NOT NULL,
    oxygen_saturation       DECIMAL(4, 1) NOT NULL,
    creation_time           TIMESTAMP     NOT NULL,
    record_expiration_epoch BIGINT        NOT NULL
);

CREATE INDEX ASYNC IF NOT EXISTS idx_patient_vitals_patient_id
    ON vital_fold.patient_vitals (patient_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_patient_vitals_clinic_id
    ON vital_fold.patient_vitals (clinic_id);
